### PR TITLE
Clear index

### PR DESCRIPTION
**Pull request by ayushanand308**
This helps us clearing and rebuilding the help and completion indexes.

### CODE REVIEW

**Comment by ayushanand308** [comment]
The placement of the button and whether to keep it as a button or make it a checkbox instead are still to be discussed.

**Comment by agraef** [comment]
First some cosmetic stuff (missing whitespace):

~~~diff
--- a/pd/nw/pdgui.js
+++ b/pd/nw/pdgui.js
@@ -595,8 +595,8 @@ function rebuild_index(clear_index = false)
     index = init_elasticlunr();
     index_started = index_done = false;
 
-    if(clear_index){
-        completion_list=[];
+    if (clear_index) {
+        completion_list = [];
         completion_index = new fuse(completion_list,autocomplete_index_options);
     }
 ~~~

I'd also change index, index_tt to clear_index, clear_index_tt for clarity.

I'm no native English speaker, but shouldn't the tooltip text be "Clear the help and completion index**es**" (the "and" conjunction indicates plural, doesn't it?).

**Comment by agraef** [comment]
Also, I think that the rebuild_index function needs to be exported in pdgui.js if it's to be used in dialog_prefs.html.

**Comment by agraef** [comment]
Still, testing this on Linux I can't get the Clear indexes button to do anything, unless I change the name of the clear() function in dialog_prefs.html to something else. Otherwise pdgui.rebuild_index just never seems to be invoked at all. This is weird. Does it work on your side? Maybe the clear() function is already used for some internal purpose? At least on Linux where we use an older nw.js version.

Anyway, if I change `clear()` to `clear_indexes()` in dialog_prefs.html then everything works fine on Linux as well.

**Comment by agraef** [comment]
> The placement of the button and whether to keep it as a button or make it a checkbox instead are still to be discussed.

Yes, I think that button should go into the GUI tab. Can you try adding it at the bottom of the GUI tab, please?

Other than that, I think that this should be ready to be merged. (After fixing the issues listed above and rebasing on the current testing branch.) Good job!

**Comment by agraef** [comment]
Here are the other changes that I'd suggest, in summary:

~~~diff
diff --git a/pd/nw/dialog_prefs.html b/pd/nw/dialog_prefs.html
index a54449b17..9f6212190 100644
--- a/pd/nw/dialog_prefs.html
+++ b/pd/nw/dialog_prefs.html
@@ -540,7 +540,7 @@ select {
         <button type="button" onClick="cancel()" data-i18n="[title]prefs.close_tt">
           <span data-i18n="prefs.close"></span>
         </button>
-        <button type="button" onclick="clear()" data-i18n="[title]prefs.index_tt">
+        <button type="button" onClick="clear_indexes()" data-i18n="[title]prefs.index_tt">
           <span data-i18n="prefs.index"></span>
         </button>
       </div>
@@ -566,7 +566,7 @@ function ok() {
     cancel();
 }
 
-function clear() {
+function clear_indexes() {
     pdgui.rebuild_index(true);
 }
 
diff --git a/pd/nw/locales/en/translation.json b/pd/nw/locales/en/translation.json
index 545cb99e4..29609362f 100644
--- a/pd/nw/locales/en/translation.json
+++ b/pd/nw/locales/en/translation.json
@@ -497,7 +497,7 @@
     "close": "Close",
     "close_tt": "Close the preferences dialog",
     "index": "Clear indexes",
-    "index_tt": "Clear the help and completion index"
+    "index_tt": "Clear the help and completion indexes"
   },
   "font": {
     "prop": {
diff --git a/pd/nw/pdgui.js b/pd/nw/pdgui.js
index 49f5bf183..19d11685d 100644
--- a/pd/nw/pdgui.js
+++ b/pd/nw/pdgui.js
@@ -595,8 +595,8 @@ function rebuild_index(clear_index = false)
     index = init_elasticlunr();
     index_started = index_done = false;
 
-    if(clear_index){
-        completion_list=[];
+    if (clear_index) {
+        completion_list = [];
         completion_index = new fuse(completion_list,autocomplete_index_options);
     }
 
@@ -615,6 +615,8 @@ function rebuild_index(clear_index = false)
     }
 }
 
+exports.rebuild_index = rebuild_index;
+
 // this is called from the gui tab of the prefs dialog
 function update_browser(doc_flag, path_flag, ac_flag, ac_prefix_flag, ac_relevance_flag)
 {
~~~

**Comment by agraef** [comment]
Forgot the change from change index, index_tt to clear_index, clear_index_tt there.

**Comment by agraef** [comment]
Ok, I gave it another go myself, here's how it looks like:

image

Note that I also changed the label to "Reset indexes", so that it doesn't sound like you'd be left with a completely empty index afterwards.

**Comment by agraef** [comment]
Here are the diffs with all my suggested cosmetic changes:

~~~diff
diff --git a/pd/nw/dialog_prefs.html b/pd/nw/dialog_prefs.html
index a54449b17..dac0ac437 100644
--- a/pd/nw/dialog_prefs.html
+++ b/pd/nw/dialog_prefs.html
@@ -475,6 +475,10 @@ select {
               <input type="checkbox" id="browser_init" name="browser_init">
               <span data-i18n="prefs.gui.browser.browser_init"></span>
             </label>
+            <br/><br/>
+            <button type="button" onClick="reset_indexes()" data-i18n="[title]prefs.reset_index_tt">
+	      <span data-i18n="prefs.reset_index"></span>
+            </button>
           </div>
         </div>
 
@@ -540,9 +544,6 @@ select {
         <button type="button" onClick="cancel()" data-i18n="[title]prefs.close_tt">
           <span data-i18n="prefs.close"></span>
         </button>
-        <button type="button" onclick="clear()" data-i18n="[title]prefs.index_tt">
-          <span data-i18n="prefs.index"></span>
-        </button>
       </div>
     </div>
   <script>
@@ -566,7 +567,7 @@ function ok() {
     cancel();
 }
 
-function clear() {
+function reset_indexes() {
     pdgui.rebuild_index(true);
 }
 
diff --git a/pd/nw/locales/en/translation.json b/pd/nw/locales/en/translation.json
index 545cb99e4..5c079999d 100644
--- a/pd/nw/locales/en/translation.json
+++ b/pd/nw/locales/en/translation.json
@@ -496,8 +496,8 @@
     "cancel_tt": "Cancel updating the preferences",
     "close": "Close",
     "close_tt": "Close the preferences dialog",
-    "index": "Clear indexes",
-    "index_tt": "Clear the help and completion index"
+    "reset_index": "Reset indexes",
+    "reset_index_tt": "Reset the help and completion indexes"
   },
   "font": {
     "prop": {
diff --git a/pd/nw/pdgui.js b/pd/nw/pdgui.js
index 49f5bf183..19d11685d 100644
--- a/pd/nw/pdgui.js
+++ b/pd/nw/pdgui.js
@@ -595,8 +595,8 @@ function rebuild_index(clear_index = false)
     index = init_elasticlunr();
     index_started = index_done = false;
 
-    if(clear_index){
-        completion_list=[];
+    if (clear_index) {
+        completion_list = [];
         completion_index = new fuse(completion_list,autocomplete_index_options);
     }
 
@@ -615,6 +615,8 @@ function rebuild_index(clear_index = false)
     }
 }
 
+exports.rebuild_index = rebuild_index;
+
 // this is called from the gui tab of the prefs dialog
 function update_browser(doc_flag, path_flag, ac_flag, ac_prefix_flag, ac_relevance_flag)
 {
~~~

Same diffs in a zip file (GH doesn't allow me to just upload this as a plain text file): 
[clear_indexes.zip](https://github.com/user-attachments/files/16234649/clear_indexes.zip)

Can you please commit these and rebase on the current testing branch? Then this should be ready to be merged.

**Comment by agraef** [comment]
I'm still pondering whether we should have a "Clear custom completions" checkbox along with the "Reset indexes" button. This would determine whether the completions get cleared or not, i.e. whether rebuild_index gets invoked with an argument of true or false. That way the user could determine whether he wants to keep his custom and argument completions or not, which seems useful. What do you think?

**Comment by ayushanand308** [comment]
> I'm still pondering whether we should have a "Clear custom completions" checkbox along with the "Reset indexes" button. This would determine whether the completions get cleared or not, i.e. whether rebuild_index gets invoked with an argument of true or false. That way the user could determine whether he wants to keep his custom and argument completions or not, which seems useful. What do you think?


Yes, this seems like a good addition. Users would have more control over how they want their index to be structured.I have added the checkbox. When checked, it clears all the custom objects and completions. When unchecked, it just calls the rebuild_index as it was previously called and simply rebuilds index without clearing the custom completions and arguments.[
Screenshot 2024-07-15 235446
](url)

**Comment by ayushanand308** [comment]
> Still, testing this on Linux I can't get the Clear indexes button to do anything, unless I change the name of the clear() function in dialog_prefs.html to something else. Otherwise pdgui.rebuild_index just never seems to be invoked at all. This is weird. Does it work on your side? Maybe the clear() function is already used for some internal purpose? At least on Linux where we use an older nw.js version.
> 
> Anyway, if I change `clear()` to `clear_indexes()` in dialog_prefs.html then everything works fine on Linux as well.

The reason for the issue might be that after making changes locally in the non-git folder, I just copy those changes to this repository. So, I might have missed copying some lines correctly.

**Comment by agraef** [comment]
Looks good. Maybe change 'Clear the completions:' to just 'Clear completions' without the colon. Please push, then I'll merge.

**Comment by agraef** [comment]
Also, 'Reset index' for consistency with capitalization elsewhere in the dialog.

**Comment by agraef** [comment]
You forgot the `if (clear_index) {` edit.

But there are two more serious issues with your changes to pd/nw/dialog_prefs.html which break the communication between engine and gui:

- You added an extra argument `get_bool_elem("reset_init")` in the call `pdgui.pdsend("pd gui-prefs", ...)` at line 834. This is a call to a Pd method somewhere in the C code which doesn't have that argument. You need to get rid of that line.

- Likewise, you added an extra `reset_init` argument to the gui_prefs_callback() function at line 1105, but this function gets called from gui_gui_properties() in pdgui.js which doesn't pass that argument. You need to get rid of the line, as well as lines 1144-1145 where the bogus argument is being used.

I see what you were trying to do there, but that's not how any of this works. ;-)

Fortunately, in this case we don't need any communication between engine and gui for the new checkbox, it can just live in the gui and that's ok. So just get rid of the extra arguments in these two places and your code should be fine.

I can explain how the actual communication between engine (the C side) and gui (the JS side) works, because we'll actually need this for the tooltips checkbox that we still want to add. In contrast to the reset_init checkbox, the tooltips flag *will* need to be stored in the permanent config data which is maintained by the engine, hence in this case we'll need to go through the whole `pd gui-prefs` - `gui_gui_properties` rigmarole to implement that. Yes, you'll have to do some changes on the C side there, but this will not be complicated, I promise. :) Let's talk about this in our meeting today, ok?

In the meantime, just get rid of line 834, the edit in line 1105, and lines 1144-1145, then everything should be fine.

**Comment by agraef** [comment]
Just to be clear, here are my suggested changes:

~~~diff
diff --git a/pd/nw/dialog_prefs.html b/pd/nw/dialog_prefs.html
index 3388495cd..0f99600e3 100644
--- a/pd/nw/dialog_prefs.html
+++ b/pd/nw/dialog_prefs.html
@@ -572,11 +572,7 @@ function ok() {
 }
 
 function reset_indexes() {
-  if (get_bool_elem("reset_init")) {
-    pdgui.rebuild_index(true);
-  } else {
-    pdgui.rebuild_index();
-  }
+    pdgui.rebuild_index(get_bool_elem("reset_init"));
 }
 
 function gui_preset_change(elem) {
@@ -831,7 +827,6 @@ function apply(save_prefs) {
         get_bool_elem("browser_doc"),
         get_bool_elem("browser_path"),
         get_bool_elem("browser_init"),
-        get_bool_elem("reset_init"),
         get_autopatch_yoffset()
     );
     // Also send the browser config to the GUI, so that it will update the
@@ -1102,7 +1097,7 @@ function autopatch_yoffset_toggle(checked) {
 
 function gui_prefs_callback(name, show_grid, grid_size, save_zoom,
     autocomplete, autocomplete_prefix, autocomplete_relevance,
-    browser_doc, browser_path, browser_init, reset_init, autopatch_yoffset) {
+    browser_doc, browser_path, browser_init, autopatch_yoffset) {
     var s = document.getElementById("gui_preset");
 
     // ag: scan the css subdir for user-defined styles
@@ -1141,8 +1136,6 @@ function gui_prefs_callback(name, show_grid, grid_size, save_zoom,
     document.getElementById("browser_doc").checked = !!browser_doc;
     document.getElementById("browser_path").checked = !!browser_path;
     document.getElementById("browser_init").checked = !!browser_init;
-    document.getElementById("reset_init").checked = !!reset_init;
-
 
     if (+autopatch_yoffset !== 0) {
         document.getElementById("autopatch_yoffset_value").value =
diff --git a/pd/nw/pdgui.js b/pd/nw/pdgui.js
index d121960e6..19d11685d 100644
--- a/pd/nw/pdgui.js
+++ b/pd/nw/pdgui.js
@@ -595,7 +595,7 @@ function rebuild_index(clear_index = false)
     index = init_elasticlunr();
     index_started = index_done = false;
 
-    if(clear_index){
+    if (clear_index) {
         completion_list = [];
         completion_index = new fuse(completion_list,autocomplete_index_options);
     }
~~~

I just tested this, and it seems to work alright.

**Comment by ayushanand308** [comment]
I've made the necessary changes! Sorry for the mess.

**Comment by agraef** [comment]
No worries, you're doing fine. :) Unfortunately, that part of the code is a bit messy anyway.

**Comment by agraef** [comment]
I just noticed that reset_index(_tt) ended up in the wrong section of the translations, it should be moved up to where the translations for the checkbox are. I'll take care of this when I add the German and French translations.

**Comment by agraef** [comment]
Done, cf. rev. 150486a.

**Comment by agraef** [comment]
Ok, I just fixed the mess I made with the previous commit, the corrected one is here: rev. d442ffd

So you can go ahead now. :wink: Note that I force-pushed to the testing branch, so you may have to base your PRs on a fresh checkout of that branch.

**Pull request merged**
