### PR TITLE
Tooltip checkbox

### PR DESCRIPTION
**Pull request by ayushanand308**
Added a checkbox in preference dialog to enable and disable tooltips for objects in auto-completion dropdown.

### CODE REVIEW

**Comment by ayushanand308** [comment]
This ended up being way messier  than I thought it would be :(

**Comment by agraef** [comment]
Yeah, but it doesn't look too bad. :)

There's some old stuff in your branch (everything related to the index reset stuff) which I already merged in your previous PR, and which presumably also causes the merge conflicts. Please make sure to remove that from your PR (rev. 356b303d4f0ef6cd6890ad8dd6684c1494c8f629). The rest looks ok at first glance to me, but I can only test this after you removed the old commit.

**Comment by agraef** [comment]
Wait, I might as well merge this manually via git and get rid of the old commit during that. Stay tuned.

**Comment by agraef** [comment]
Hmm yes, it seems that you branched off of an old version of the testing branch which didn't have any of your previous commits yet, so they're all back from the dead. ;-) Looks like https://github.com/agraef/purr-data/pull/40/commits/d839de372ee626782067eb5dc02665aa9c8da527 is all I need, so I can just cherry-pick that and we should be fine.

**Comment by agraef** [comment]
Ok, I see now what the problem is. Your rev. 4aeb650d180aca0f854c2167ff6e85be9d4ddddb had the reset_index translations in the wrong place (directly under prefs instead of prefs.gui.browser), which I corrected in https://github.com/agraef/purr-data/commit/f816920cb03656d77487b5aa347f6e06ad29fbdf. That's causing the merge conflicts I guess. We'll keep getting those until you rebase your development branch with my current https://github.com/agraef/purr-data/tree/testing branch. Maybe do that before you submit your next PR. Git can be confusing at times. :)

**Comment by agraef** [comment]
Merged manually in rev. babb8c55eeb8e484f65488296a1fa7d9ada6bcc5. Also added German and French translations in rev. 7e39e17d10ce3583a2eb2186023769fc20bd4c47. Thanks!

**Comment by agraef** [comment]
Well, this is giving me compile errors:

~~~
s_file.c: In function ‘sys_loadpreferences’:
s_file.c:720:32: error: ‘sys_autocomplete_tooltip_enabled’ undeclared (first use in this function); did you mean ‘autocomplete_sys_tooltip_enabled’?
  720 |         sscanf(prefbuf, "%d", &sys_autocomplete_tooltip_enabled);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                autocomplete_sys_tooltip_enabled
s_file.c:720:32: note: each undeclared identifier is reported only once for each function it appears in
s_file.c: In function ‘glob_savepreferences’:
s_file.c:910:25: error: ‘sys_autocomplete_tooltip_enabled’ undeclared (first use in this function); did you mean ‘autocomplete_sys_tooltip_enabled’?
  910 |     sprintf(buf1, "%d", sys_autocomplete_tooltip_enabled);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         autocomplete_sys_tooltip_enabled
make[3]: *** [makefile:125: s_file.o] Error 1
~~~

Seems to be a typo somewhere. Did you actually try to compile this? Just a `make light` should have revealed this.

**Comment by agraef** [comment]
Most IDEs will also flag such compile errors right there in the editor. Emacs with FlyCheck found it, too, without having to run `make`. ;-) What code editor are you using?

**Comment by agraef** [comment]
Fixed in rev. 32361df4bd899c860f58aff67ee5dde2bcfbdf97. Tested on Linux, Mac, and Windows. Looking good!

Looking forward to your fuzzy matching PR! :)

**Comment by agraef** [comment]
BTW, I also just fixed the problem with the index not being rebuilt with the operations in the GUI preferences. (rev. e30a25461979685ce910eafc6513ae18037b5779)

**Comment by agraef** [comment]
I wonder how that could go unnoticed for so long. :) Thanks for bringing that up!

**Comment by ayushanand308** [comment]
> Well, this is giving me compile errors:
> 
> ```
> s_file.c: In function ‘sys_loadpreferences’:
> s_file.c:720:32: error: ‘sys_autocomplete_tooltip_enabled’ undeclared (first use in this function); did you mean ‘autocomplete_sys_tooltip_enabled’?
>   720 |         sscanf(prefbuf, "%d", &sys_autocomplete_tooltip_enabled);
>       |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                autocomplete_sys_tooltip_enabled
> s_file.c:720:32: note: each undeclared identifier is reported only once for each function it appears in
> s_file.c: In function ‘glob_savepreferences’:
> s_file.c:910:25: error: ‘sys_autocomplete_tooltip_enabled’ undeclared (first use in this function); did you mean ‘autocomplete_sys_tooltip_enabled’?
>   910 |     sprintf(buf1, "%d", sys_autocomplete_tooltip_enabled);
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                         autocomplete_sys_tooltip_enabled
> make[3]: *** [makefile:125: s_file.o] Error 1
> ```
> 
> Seems to be a typo somewhere. Did you actually try to compile this? Just a `make light` should have revealed this.

🤔,I tested this with "tooltip_enabled", but before committing I changed it to "autocomplete_tooltip_enabled" and pushed it. Maybe that's when this error crept in.

**Comment by agraef** [comment]
Lesson from this: Always test your last minute fixes. :stuck_out_tongue_winking_eye: 

Ok, looking forward to the fuzzy completions! Once those are in, I can go about updating the screenshots as well as the browser and autocompletion sections in https://agraef.github.io/purr-data-intro/.

**Comment by agraef** [comment]
Corrected some wrong indentation and trailing whitespace in rev. 6df68ceed85b2a73703de4a5f2564e7478e47c2e. The latter may seem a bit pedantic, but git diff flags trailing whitespace in a red color which is rather distracting. :)

I also noticed a regression in rev. 9bd1dd6cafbb2f293c42e6dea9b67291c6458d59 that caused alt+home/end to break. Well, they are not really broken, but they are still the old implementation which re-creates the dropdown with just a limited number of items, so the scrollbar and the highlighting just disappears:

alt+home-end-bug

I think that we should just get rid of those bindings. They were useful in the olden days when the popdown didn't have a scrollbar, but now they just seem non-standard and out of place. I'll take care of that and you concentrate on the fuzzy matching stuff. :)

**Comment by agraef** [comment]
Done (rev. 1e52b3054118a617cbf1b669dde238bd85f13341).

Ok, now that my testing branch has diverged quite a bit from yours, you should really sync your source with my upstream again, and then branch off your next PR / feature branch from that. Are you familiar with how that works? You can actually sync a branch in your fork in GH's web interface, do you know how to do that?

**Comment by agraef** [comment]
Ok, I started working on updating the text of the tutorial, see rev. https://github.com/agraef/purr-data-intro/commit/cbc83324967d32e39a5380133115057c6c76bc4a, the text in its current state is here: https://github.com/agraef/purr-data-intro/blob/master/Purr-Data-Intro.md. If you notice any typos, errors or omissions there, I'd appreciate it if you could send me a PR there, but that can wait until the "fuzzy matching" stuff has landed. Now I'm waiting as fast as I can. :)

**Pull request closed without merging**
