### PR TITLE
French menu item

### PR DESCRIPTION
**Pull request by trebmuh**
Hope that helps

### CODE REVIEW

**Comment by agraef** [comment]
Sorry, somehow I never reacted to this. But note this is just a mirror of Jonathan's upstream repo at https://git.purrdata.net/jwilkes/purr-data, so could you please submit your PR there? Thanks.

**Comment by trebmuh** [comment]
Hi @agraef ,
I'd like to not subscribe to another upstream repo for such as small code change if possible. Would you be able to cherry pick from here or to give a ML address I can send the patch to without having to subscribe please?

**Comment by agraef** [comment]
@trebmuh I finally got around to submitting this upstream at https://git.purrdata.net/jwilkes/purr-data/-/merge_requests/422. Note that I squashed your changeset to a [single commit](https://git.purrdata.net/jwilkes/purr-data/-/merge_requests/422/diffs?commit_id=e820732ae3722897a9ee7e990fae35391855e3ce) and also added corresponding German translations for the same items in [this commit](https://git.purrdata.net/jwilkes/purr-data/-/merge_requests/422/diffs?commit_id=ca582faf61a67788bc0779d739f5fa53c763dcb2). Again, thanks a bunch for your contribution!

**Comment by trebmuh** [comment]
Thank you very much @agraef !

**Pull request closed without merging**
