### PR TITLE
added tooltip 

### PR DESCRIPTION
**Pull request by ayushanand308**
Added tooltip for auto-completion menu results to show objects description.

### CODE REVIEW

**Comment by agraef** [comment]
This is looking good, but I have some minor gripes:

- For consistency with existing coding style, please add spaces around the equals sign in assignment (i.e., `var obj_ = new Map();`), and after a comma in the argument list (e.g., `obj_.set(title, desc)`, there are a couple of those). This also improves readability.
- We should maybe find a more descriptive name for the `obj_` variable, and also add a comment which describes the purpose. Maybe something like this?
    ~~~javascript
    // object descriptions by title for the autocompletion menu; computed on the fly during index construction
    var ac_tooltips = new Map();
    ~~~

**Comment by ayushanand308** [comment]
I have made the required changes!

**Comment by ayushanand308** [comment]
I removed the tooltip, but the issue persisted, only occurring when clicking on the highlighted part of the text. It seems to be caused by the text highlighting. I used the <span> element to highlight the text, which might not be getting registered correctly in pd_canvas events. I will add the fix for this :)

**Comment by agraef** [comment]
Yes, I can confirm that, also on Linux, the text highlighting gets in the way with or without the tooltips. Do you already have an idea on how to fix this?

**Comment by ayushanand308** [comment]
In the text_mousedown event in pd_canvas, if we specifically target the span element inside the autocomplete dropdown, it successfully selects the result even when clicking on the highlighted part.

**Pull request merged**
