### PR TITLE
Adds touch support (WIP)

### PR DESCRIPTION
**Pull request by spidercatnat**
Leaves method names alone, but adds pointer_x and pointer_y variables that get coordinates from touch or mouse events.

### CODE REVIEW

**Comment by agraef** [comment]
Hi @spidercatnat, thanks for your contribution! I don't actually maintain the sources here, this repo is just a mirror of Jonathan's upstream in gitlab at https://git.purrdata.net/jwilkes/purr-data. I would kindly ask you to submit your pull request there, so that Jonathan can review it (he's written the JS part and so is probably the best person to review it anyway).

**Comment by agraef** [comment]
@spidercatnat I've tested this on my Lenovo X1 Yoga now, which has a touchscreen, and it seems to work nicely indeed. I'm a bit worried about potential ill side-effects in rev. a8d2b052c67b8d67fb67917016215f5b966c9b8e, but Jonathan might be able to say more about this.

I can commit your PR (with some trivial whitespace fixes added) upstream for you, if you want; just let me know.

**Comment by spidercatnat** [comment]
@agraef Let's hold the commit, as we've currently found some kinks that need to be ironed out that have to do with the way Chromium dispatches simultaneous click and touch events, as well as the side effects mentioned with regards to the pulldowns. The first should be workable, and any insight from Jonathan on the latter is greatly appreciated.

**Comment by agraef** [comment]
Yes, I noticed some hitches, too. E.g., touching the buttons in the "Do you want to save the changes ..." confirmation dialog stopped working. So there seem to be more cases that need fixes similar to those in rev. a8d2b05. I hope that you can find these and fix them, because it would be really nice to have proper touch support in Purr Data!

**Comment by agraef** [comment]
@spidercatnat are you finished with this yet? Otherwise I'd suggest to mark the PR as "WIP" in the title.

**Comment by agraef** [comment]
I think that some of the changes (especially the last two commits) will interfere with Ico Bukvic's revamping of the scrollbars which went into upstream recently, so there's a lot of integration work ahead. ;-) Nevertheless, I consider this important, so I'll submit a bug report upstream, pointing to this PR, and then we'll see what happens.

**Comment by agraef** [comment]
In the meantime, could you please rebase your branch on 2.11.0 (`git rebase 2.11.0 && git push -f`)? I already tested that this will work, and it will at least make your branch compile with gcc 10 again.

**Comment by agraef** [comment]
Reported upstream at https://git.purrdata.net/jwilkes/purr-data/-/issues/659.

**Comment by agraef** [comment]
@spidercatnat I'm doing the same offer here as on Gitlab: I'm willing to offer a 50 Eur bounty, payable by Paypal, to anyone who is the first to make proper touch support work (on the current master, with the bugs in your branch ironed out). ;-)

**Comment by agraef** [comment]
Actually, the rebase conflict with the current master was very easy to resolve (just keep both HEAD and your branch, and you're fine), results now here: https://bitbucket.org/agraef/purr-data/branch/spidercatnat-touch-support

**Comment by agraef** [comment]
@spidercatnat I was able to fix the regression with the touch events in the confirmation popup myself, you can find that in rev. 6f490416b6bd856d6d323f209cfd0ec755812cdf in my (rebased) copy of your branch. As you can see, I pulled the rebased branch to Github now, so that we can keep track of regressions and other bugs related to your PR more easily.

In fact, I already ran into another issue, namely that dragging, say, a slider in a scrolled window pulls along the scrollbars as well. It goes without saying that this makes it really hard to operate the slider while the canvas beneath keeps moving along, so to speak. ;-)

But we're getting closer.

**Comment by agraef** [comment]
Here's what I mean:

drag-slider

Here I'm simply trying to drag a slider (first the `mix` and then the `moddepth` slider), but that doesn't really work out because of the interfering scrolling events.

Can you reproduce this? I'm still looking for the event handler where this happens, maybe we can conditionally disable the default handler/propagation there. If you have any idea on how to fix this, I'm all ears. :)

**Comment by agraef** [comment]
It looks like the issue above, i.e., dragging along the viewport when operating a slider, might at least be partially fixed by switching to the latest nw.js (I tried with 0.47-beta1). So this might either be a regression in Ico's changeset that recently went into master, or a bug in the older nw.js version (0.24.4) that we're using by default on Linux right now, or a combination of both. I'll have to do more testing to see what's the actual root cause here. But even with the latest nw.js, the issue remains when dragging vertically. :(

**Comment by agraef** [comment]
Rebased once more since upstream updated master. I've also renamed my copy to https://github.com/agraef/purr-data/tree/touch-support-master now, so that it's clear that it's not identical with your branch, and what it's based on. Also pulled over your original branch as https://github.com/agraef/purr-data/tree/spidercatnat-touch-support, just for the record.

I've tested this with various bases now: [2.11.0](https://github.com/agraef/purr-data/commits/2.11.0) (which is the earliest version that still compiles with gcc 10.1.0 for me), rev.  [11f6610](https://github.com/agraef/purr-data/commits/11f6610) (which is just before Ico's branch with updates for nw.js 0.46/0.47 was merged back in), and the current master. The behaviour is always the same, so it's pretty clear that the glitches of the touch support that I reported above are *not* regressions because of code that went into master very recently.

**Comment by agraef** [comment]
I also noticed another issue: Dragging the IEM GUI label handles in edit mode doesn't work:

touch-drag-iemgui-handle

I thought that this was because there's no special code for touch events in iemgui_label_mousemove, so I tried to add that, but this didn't really help much either (the label still didn't move at all, until I clicked with the mouse):

~~~diff
diff --git a/pd/nw/pd_canvas.js b/pd/nw/pd_canvas.js
index e874d8f0..78f51a50 100644
--- a/pd/nw/pd_canvas.js
+++ b/pd/nw/pd_canvas.js
@@ -497,8 +497,11 @@ var canvas_events = (function() {
                 //      handle (which will eventually get erased by Pd anyway).
                 //      Anyhow, this is all very bad, but it works so it's
                 //      at least not the worst of all possible worlds.
-                var dx = (evt.pageX + svg_view.x) - last_draggable_x,
-                    dy = (evt.pageY + svg_view.y) - last_draggable_y,
+                let [pointer_x, pointer_y] = evt.type === "touchstart"
+                    ? [evt.touches[0].pageX, evt.touches[0].pageY]
+                    : [evt.pageX, evt.pageY];
+                var dx = (pointer_x + svg_view.x) - last_draggable_x,
+                    dy = (pointer_y + svg_view.y) - last_draggable_y,
                     handle_elem = document.querySelector(
                         draggable_label ?
                             ".move_handle" :
@@ -510,12 +513,12 @@ var canvas_events = (function() {
                         getElementsByClassName("gop_drag_handle").length ?
                         true : false;
 
-                last_draggable_x = evt.pageX + svg_view.x;
-                last_draggable_y = evt.pageY + svg_view.y;
+                last_draggable_x = pointer_x + svg_view.x;
+                last_draggable_y = pointer_y + svg_view.y;
 
                 pdgui.pdsend(target_id, "_motion",
-                    (evt.pageX + svg_view.x),
-                    (evt.pageY + svg_view.y));
+                    (pointer_x + svg_view.x),
+                    (pointer_y + svg_view.y));
             },
             iemgui_label_mouseup: function(evt) {
                 //pdgui.post("lifting the mousebutton on an iemgui label");
~~~

So I have no idea how to fix that either. :(

On the positive side, I didn't actually notice any obvious misbehaviour because of rev. a8d2b052c67b8d67fb67917016215f5b966c9b8e, which you were worried about, so we might be good there. I must admit, though, that I didn't test the touch behaviour of dropdown menus very thoroughly yet.

**Comment by agraef** [comment]
So, to summarize: We've got one bug down (the untouchable buttons in the confirmation dialog, which I fixed in rev. 6f732d2d0cd8c0122612245f8b7015b3afb24a94), and at least the following remaining issues (see my remarks above for all the gory details):

- with edit mode off, operating GUI elements like dragging a slider triggers scroll events, which makes touch rather unusable if the canvas is larger than its viewport

- with edit mode on, dragging iemgui label handles doesn't work

I'm afraid that even if we don't care too much about edit mode for now, the first issue is a real showstopper, because operating the GUI elements using touch *is* probably the single most important feature that Purr Data currently lacks. So I hope that you can figure out a way to fix that. That 50€ bounty that I put up can still be yours. ;-)

Unfortunately, I don't think that we can rely on Jonathan's input on this PR right now, because he's really busy conducting the Purr Data Google Summer of Code projects.

**Comment by agraef** [comment]
Unfortunately, I just found that disabling the `evt.preventDefault()` call for touch events causes touch-clicks on iemgui objects like bangs and toggles to register *twice*, so my proposed fix for the confirmation dialog buttons in rev. 6f732d2 is too simplistic. :( Well, maybe I can still save it by figuring out a way to detect whether the event actually goes to the canvas itself or the confirmation popup. I'll give that a shot.

**Comment by agraef** [comment]
@spidercatnat Are you still on board with this? If I'm only talking to myself here then we won't be able to make much progress with your PR. ;-) I really need your help with these issues, because you surely know a whole lot more about these event handlers than I do.

**Comment by agraef** [comment]
Ok, I think I finally have a proper fix for the confirmation popup bug now, see rev. 15971b923dc85eed0921ac5418631b383a6b87a9. A similar approach might also work for the other two bugs, I'm investigating...

**Comment by agraef** [comment]
Alright, it seems that I've finally fixed all the remaining issues that I noticed in rev. 04e759e78deafb8649914cf961582e8f41d2c0f4. There are still a few snags, specifically:

- Dragging iemgui labels in edit mode still needs quite some faffing about, as detailed in the commit message. This is probably due to the way this operation is handled in the FUDI protocol, going back and forth between GUI and engine, so there's probably not much we can do about this in the present implementation.

- In some cases it's hard to hit the exact spot to initiate a dragging action, especially in edit mode.

But it certainly seems usable know.

So, sorry folks, but that 50€ bounty *is* gone now. :( I might put up another one in the future for implementing multi-touch, though, if anyone is interested. However, it seems that this might be a medium-sized project in itself, which might better be suited for next years' GSoC. Anyway, if anyone is interested in this, please get in touch (no pun intended, haha), or leave a message here.

@spidercatnat I'm closing this PR now and will pull my version of the branch over to Jonathan's Gitlab, so that I can submit a pull request there. If you want to follow along, make sure to watch out for it on https://git.purrdata.net/jwilkes/purr-data. Again, thanks a lot for your contribution, it's very much appreciated! :)

**Comment by agraef** [comment]
Merge request now up at Gitlab, see https://git.purrdata.net/jwilkes/purr-data/-/merge_requests/430.

**Comment by spidercatnat** [comment]
@agraef Thank you for all of this! I'll have to carefully read over your work when I get the chance. I've been very busy with gearing up for an internship and working towards a v1 release at work but I would love to contribute when time permits. 

PS: Regarding nw.js version, if there exists a more up-to-date NW.js compiled for armv7l then we could simplify the code by using the PointerEvents API.

Best regards

**Comment by agraef** [comment]
Yeah, we're actually testing the nw.js 0.47 beta right now, but that still trips some performance regressions in Purr Data. Also, switching to PointerEvents probably needs a complete rewrite of the mouse event handlers. But you're right, if we want to get multi-touch, it's probably the way to go.

Best wishes for your internship!

**Pull request closed without merging**
